apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    kind: service
    type: db-service
spec:
  selector:
    kind: db
  ports:
  - port: 5432
    name: psql

---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: general
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: europe-west1-b

---
kind: PersistentVolumeClaim
metadata:
  name: db
  annotations:
    volume.beta.kubernetes.io/storage-class: general
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: general
  resources:
    requests:
      storage: 30Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  template:
    metadata:
      labels:
        kind: db
    spec:
      containers:
      - image: aidbox/aidboxdb:a16f30a349beae287bea3011a2cdeff177a8f54a
        name: aidboxdb
        ports:
        - containerPort: 5432
          name: psql
        volumeMounts:
        - name: db
          mountPath: /data
          subPath: pgdata
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db
